# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13fca575dc3d6492791b47694f7af9f339db013f7890e88d0e9d2eb990f735f5f6f0ed3f79b8e79e2730ce40d92676c2174f669fe92972b92b1a8526aeb3471d

test:
  secret_key_base: b1dc919010a206ece2b6c99aa034673ecbe750766249ee9cbcb993030615b4b717dab4206566db577f79038c7e810b5a3f79b365981716cb5f91d6582e3342b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
